/* 系统管理初始化脚本 */

-- 机构
INSERT INTO sys_org (org_id, org_name, org_type, parent_id, sort, area_id, area_name) VALUES ('manager_100000', '管理平台', 'platform', '0', 1, '0', '中华人民共和国');

-- 用户
INSERT INTO sys_user (user_id, password, real_name, gender, birthday, org_id, org_name, area_id, area_name, enable) VALUES ('admin', '953c3993b756e2689f4a31a6329554e1', '系统管理员', '男', '1999-12-31', 'manager_100000', '管理平台', '0', '中华人民共和国', 1);

-- 角色
INSERT INTO sys_role (role_id, role_name, enable, description) VALUES ('admin', '系统管理员', 1, '系统管理员为整个系统最高权限者');

-- 权限
INSERT INTO sys_auth (auth_id, auth_type, relate_type, auth_mode, object_id, object_name) VALUES ('1', 'func', 'user_role', 'in', 'admin', '系统管理员');
INSERT INTO sys_auth (auth_id, auth_type, relate_type, auth_mode, object_id, object_name) VALUES ('2', 'func', 'role_func', 'all', 'admin', '系统管理员');

-- 关联关系
INSERT INTO sys_relate (object_id, target_id, relate_type) VALUES ('admin', 'admin', 'user_role');

-- 存储板块
INSERT INTO sys_bucket (bucket, name, storage, description) VALUES ('system.app.version', '应用版本', 'mongo_gridfs', '应用版本文件存储板块');

-- 字典
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('system_flag', '系统标识', '-', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('manager', '后台管理', 'system_flag', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('func_type', '功能类型', '-', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('sys', '系统', 'func_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('dir', '目录', 'func_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('menu', '菜单', 'func_type', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('btn', '按钮', 'func_type', 4);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('log_type', '日志类型', '-', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('opreation', '操作日志', 'log_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('exception', '异常日志', 'log_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('org_type', '机构类型', '-', 4);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('platform', '平台机构', 'org_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('supervise', '监管机构', 'org_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('operate', '运营机构', 'org_type', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('auth_type', '权限类型', '-', 5);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('func', '功能权限', 'auth_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('api', '接口权限', 'auth_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('data', '数据权限', 'auth_type', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('relate_type', '关系类型', '-', 6);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('user_role', '用户角色关系', 'relate_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('role_func', '角色功能关系', 'relate_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('func_api', '功能接口关系', 'relate_type', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('auth_mode', '权限模式', '-', 7);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('all', '全量', 'auth_mode', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('none', '无', 'auth_mode', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('in', '包含', 'auth_mode', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('exc', '排他', 'auth_mode', 4);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('storage_type', '存储类型', '-', 8);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('system_file', '系统文件', 'storage_type', 1);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('mongo_gridfs', 'MongoDB文件存储', 'storage_type', 2);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('aliyun_oss', '阿里云对象存储', 'storage_type', 3);
INSERT INTO sys_dict (code, name, parent_id, sort) VALUES ('qiniu_oss', '七牛云对象存储', 'storage_type', 4);

-- 功能
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01', '后台管理', 'sys', '0', 'manager', NULL, NULL, NULL, 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0101', '权限管理', 'dir', '01', 'manager', 'el-icon-film', '#', NULL, 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010101', '机构管理', 'menu', '0101', 'manager', 'el-icon-office-building', '/auth/org', NULL, 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010101', '查询', 'btn', '010101', 'manager', NULL, NULL, 'auth:org:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010102', '新增', 'btn', '010101', 'manager', NULL, NULL, 'auth:org:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010103', '修改', 'btn', '010101', 'manager', NULL, NULL, 'auth:org:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010104', '删除', 'btn', '010101', 'manager', NULL, NULL, 'auth:org:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010102', '用户管理', 'menu', '0101', 'manager', 'el-icon-user', '/auth/user', NULL, 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010201', '查询', 'btn', '010102', 'manager', NULL, NULL, 'auth:user:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010202', '增加', 'btn', '010102', 'manager', NULL, NULL, 'auth:user:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010203', '修改', 'btn', '010102', 'manager', NULL, NULL, 'auth:user:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010204', '删除', 'btn', '010102', 'manager', NULL, NULL, 'auth:user:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010205', '重置密码', 'btn', '010102', 'manager', NULL, NULL, 'auth:user:pwd', 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010206', '角色分配', 'btn', '010102', 'manager', NULL, NULL, 'auth:user:role', 6, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010103', '角色管理', 'menu', '0101', 'manager', 'el-icon-s-custom', '/auth/role', NULL, 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010301', '查询', 'btn', '010103', 'manager', NULL, NULL, 'auth:role:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010302', '新增', 'btn', '010103', 'manager', NULL, NULL, 'auth:role:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010303', '修改', 'btn', '010103', 'manager', NULL, NULL, 'auth:role:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010304', '删除', 'btn', '010103', 'manager', NULL, NULL, 'auth:role:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010305', '功能分配', 'btn', '010103', 'manager', NULL, NULL, 'auth:role:func', 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010104', '功能管理', 'menu', '0101', 'manager', 'el-icon-menu', '/auth/func', NULL, 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010401', '查询', 'btn', '010104', 'manager', NULL, NULL, 'auth:func:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010402', '增加', 'btn', '010104', 'manager', NULL, NULL, 'auth:func:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010403', '修改', 'btn', '010104', 'manager', NULL, NULL, 'auth:func:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010404', '删除', 'btn', '010104', 'manager', NULL, NULL, 'auth:func:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010405', '接口分配', 'btn', '010104', 'manager', NULL, NULL, 'auth:func:api', 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010105', '接口管理', 'menu', '0101', 'manager', 'el-icon-s-operation', '/auth/api', NULL, 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010501', '查询', 'btn', '010105', 'manager', NULL, NULL, 'auth:api:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010502', '新增', 'btn', '010105', 'manager', NULL, NULL, 'auth:api:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010503', '修改', 'btn', '010105', 'manager', NULL, NULL, 'auth:api:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01010504', '删除', 'btn', '010105', 'manager', NULL, NULL, 'auth:api:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102', '系统管理', 'dir', '01', 'manager', 'el-icon-monitor', '#', NULL, 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010201', '地区管理', 'menu', '0102', 'manager', 'el-icon-place', '/system/area', NULL, 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020101', '查询', 'btn', '010201', 'manager', NULL, NULL, 'sys:area:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010202', '字典管理', 'menu', '0102', 'manager', 'el-icon-notebook-2', '/system/dict', NULL, 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020201', '查询', 'btn', '010202', 'manager', NULL, NULL, 'sys:dict:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020202', '新增', 'btn', '010202', 'manager', NULL, NULL, 'sys:dict:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020203', '修改', 'btn', '010202', 'manager', NULL, NULL, 'sys:dict:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020204', '删除', 'btn', '010202', 'manager', NULL, NULL, 'sys:dict:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010203', '参数管理', 'menu', '0102', 'manager', 'el-icon-setting', '/system/param', NULL, 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020301', '查询', 'btn', '010203', 'manager', NULL, NULL, 'sys:param:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020302', '新增', 'btn', '010203', 'manager', NULL, NULL, 'sys:param:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020303', '修改', 'btn', '010203', 'manager', NULL, NULL, 'sys:param:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020304', '删除', 'btn', '010203', 'manager', NULL, NULL, 'sys:param:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010204', '日志管理', 'menu', '0102', 'manager', 'el-icon-tickets', '/system/log', NULL, 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020401', '查询', 'btn', '010204', 'manager', NULL, NULL, 'sys:log:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010205', '附件管理', 'dir', '0102', 'manager', 'el-icon-files', '#', NULL, 5, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020501', '板块管理', 'menu', '010205', 'manager', 'el-icon-s-management', '/system/attach/bucket', NULL, 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050101', '查询', 'btn', '01020501', 'manager', NULL, NULL, 'sys:bucket:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050102', '新增', 'btn', '01020501', 'manager', NULL, NULL, 'sys:bucket:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050103', '修改', 'btn', '01020501', 'manager', NULL, NULL, 'sys:bucket:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050104', '删除', 'btn', '01020501', 'manager', NULL, NULL, 'sys:bucket:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020502', '附件管理', 'menu', '010205', 'manager', 'el-icon-picture-outline', '/system/attach/attach', NULL, 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050201', '查询', 'btn', '01020502', 'manager', NULL, NULL, 'sys:attach:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050202', '新增', 'btn', '01020502', 'manager', NULL, NULL, 'sys:attach:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050203', '修改', 'btn', '01020502', 'manager', NULL, NULL, 'sys:attach:mod', 3, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('0102050204', '删除', 'btn', '01020502', 'manager', NULL, NULL, 'sys:attach:del', 4, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('010206', '版本管理', 'menu', '0102', 'manager', 'el-icon-s-unfold', '/system/appversion', NULL, 6, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020601', '查询', 'btn', '010206', 'manager', NULL, NULL, 'sys:appversion:get', 1, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020602', '新增', 'btn', '010206', 'manager', NULL, NULL, 'sys:appversion:add', 2, 1);
INSERT INTO sys_func (func_id, func_name, func_type, parent_id, sys_id, icon, path, auth, sort, display) VALUES ('01020603', '删除', 'btn', '010206', 'manager', NULL, NULL, 'sys:appversion:del', 3, 1);

-- 接口
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01', '后台管理', NULL, '0', 'manager', '后台管理');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('0101', '权限管理', NULL, '01', 'manager', '后台管理-权限管理');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010101', '机构', NULL, '0101', 'manager', '后台管理-权限管理-机构');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010101', '新增机构', '/org/add', '010101', 'manager', '后台管理-权限管理-机构-新增机构');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010102', '删除机构', '/org/del', '010101', 'manager', '后台管理-权限管理-机构-删除机构');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010103', '查询单条机构', '/org/find', '010101', 'manager', '后台管理-权限管理-机构-查询单条机构');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010104', '查询机构列表', '/org/list', '010101', 'manager', '后台管理-权限管理-机构-查询机构列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010105', '修改机构', '/org/mod', '010101', 'manager', '后台管理-权限管理-机构-修改机构');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010106', '分页查询机构', '/org/page', '010101', 'manager', '后台管理-权限管理-机构-分页查询机构');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010107', '机构上移', '/org/up', '010101', 'manager', '后台管理-权限管理-机构-机构上移');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010108', '机构下移', '/org/down', '010101', 'manager', '后台管理-权限管理-机构-机构下移');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010109', '查询机构树', '/org/tree', '010101', 'manager', '后台管理-权限管理-机构-查询机构树');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010102', '用户', NULL, '0101', 'manager', '后台管理-权限管理-用户');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010201', '新增用户', '/user/add', '010102', 'manager', '后台管理-权限管理-用户-新增用户');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010202', '删除用户', '/user/del', '010102', 'manager', '后台管理-权限管理-用户-删除用户');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010203', '查询单条用户', '/user/find', '010102', 'manager', '后台管理-权限管理-用户-查询单条用户');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010204', '查询用户列表', '/user/list', '010102', 'manager', '后台管理-权限管理-用户-查询用户列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010205', '修改用户', '/user/mod', '010102', 'manager', '后台管理-权限管理-用户-修改用户');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010206', '分页查询用户', '/user/page', '010102', 'manager', '后台管理-权限管理-用户-分页查询用户');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010207', '查询用户接口列表', '/user/getApis', '010102', 'manager', '后台管理-权限管理-用户-查询用户接口列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010208', '查询用户权限列表', '/user/getAuths', '010102', 'manager', '后台管理-权限管理-用户-查询用户权限列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010209', '查询用户角色列表', '/user/getRoles', '010102', 'manager', '后台管理-权限管理-用户-查询用户角色列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010210', '查询用户信息', '/user/getUser', '010102', 'manager', '后台管理-权限管理-用户-查询用户信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010211', '重置用户密码', '/user/resetPwd', '010102', 'manager', '后台管理-权限管理-用户-重置用户密码');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010103', '角色', NULL, '0101', 'manager', '后台管理-权限管理-角色');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010301', '新增角色', '/role/add', '010103', 'manager', '后台管理-权限管理-角色-新增角色');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010302', '删除角色', '/role/del', '010103', 'manager', '后台管理-权限管理-角色-删除角色');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010303', '查询单条角色', '/role/find', '010103', 'manager', '后台管理-权限管理-角色-查询单条角色');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010304', '查询角色列表', '/role/list', '010103', 'manager', '后台管理-权限管理-角色-查询角色列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010305', '修改角色', '/role/mod', '010103', 'manager', '后台管理-权限管理-角色-修改角色');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010306', '分页查询角色', '/role/page', '010103', 'manager', '后台管理-权限管理-角色-分页查询角色');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010104', '功能', NULL, '0101', 'manager', '后台管理-权限管理-功能');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010401', '新增功能', '/func/add', '010104', 'manager', '后台管理-权限管理-功能-新增功能');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010402', '删除功能', '/func/del', '010104', 'manager', '后台管理-权限管理-功能-删除功能');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010403', '查询单条功能', '/func/find', '010104', 'manager', '后台管理-权限管理-功能-查询单条功能');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010404', '查询功能列表', '/func/list', '010104', 'manager', '后台管理-权限管理-功能-查询功能列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010405', '修改功能', '/func/mod', '010104', 'manager', '后台管理-权限管理-功能-修改功能');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010406', '分页查询功能', '/func/page', '010104', 'manager', '后台管理-权限管理-功能-分页查询功能');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010407', '功能上移', '/func/up', '010104', 'manager', '后台管理-权限管理-功能-功能上移');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010408', '功能下移', '/func/down', '010104', 'manager', '后台管理-权限管理-功能-功能下移');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010409', '查询功能树', '/func/tree', '010104', 'manager', '后台管理-权限管理-功能-查询功能树');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010410', '查询功能菜单树', '/func/menu', '010104', 'manager', '后台管理-权限管理-功能-查询功能菜单树');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010105', '接口', NULL, '0101', 'manager', '后台管理-权限管理-接口');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010501', '新增接口', '/api/add', '010105', 'manager', '后台管理-权限管理-接口-新增接口');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010502', '删除接口', '/api/del', '010105', 'manager', '后台管理-权限管理-接口-删除接口');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010503', '查询单条接口', '/api/find', '010105', 'manager', '后台管理-权限管理-接口-查询单条接口');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010504', '查询接口列表', '/api/list', '010105', 'manager', '后台管理-权限管理-接口-查询接口列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010505', '修改接口', '/api/mod', '010105', 'manager', '后台管理-权限管理-接口-修改接口');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010506', '分页查询接口', '/api/page', '010105', 'manager', '后台管理-权限管理-接口-分页查询接口');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010507', '查询接口树', '/api/tree', '010105', 'manager', '后台管理-权限管理-接口-查询接口树');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010106', '权限', NULL, '0101', 'manager', '后台管理-权限管理-权限');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010601', '新增权限', '/auth/add', '010106', 'manager', '后台管理-权限管理-权限-新增权限');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010602', '删除权限', '/auth/del', '010106', 'manager', '后台管理-权限管理-权限-删除权限');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010603', '查询单条权限', '/auth/find', '010106', 'manager', '后台管理-权限管理-权限-查询单条权限');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010604', '查询权限列表', '/auth/list', '010106', 'manager', '后台管理-权限管理-权限-查询权限列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010605', '修改权限', '/auth/mod', '010106', 'manager', '后台管理-权限管理-权限-修改权限');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010606', '分页查询权限', '/auth/page', '010106', 'manager', '后台管理-权限管理-权限-分页查询权限');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010607', '授予权限', '/auth/authorize', '010106', 'manager', '后台管理-权限管理-权限-授予权限');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010608', '查询权限信息', '/auth/getAuth', '010106', 'manager', '后台管理-权限管理-权限-查询权限信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010107', '关联关系', NULL, '0101', 'manager', '后台管理-权限管理-关联关系');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010701', '新增关联关系', '/relate/add', '010107', 'manager', '后台管理-权限管理-关联关系-新增关联关系');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010702', '删除关联关系', '/relate/del', '010107', 'manager', '后台管理-权限管理-关联关系-删除关联关系');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010703', '查询单条关联关系', '/relate/find', '010107', 'manager', '后台管理-权限管理-关联关系-查询单条关联关系');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010704', '查询关联关系列表', '/relate/list', '010107', 'manager', '后台管理-权限管理-关联关系-查询关联关系列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010705', '修改关联关系', '/relate/mod', '010107', 'manager', '后台管理-权限管理-关联关系-修改关联关系');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010706', '分页查询关联关系', '/relate/page', '010107', 'manager', '后台管理-权限管理-关联关系-分页查询关联关系');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01010707', '查询关联关系目标编号列表', '/relate/getTargetList', '010107', 'manager', '后台管理-权限管理-关联关系-查询关联关系目标编号列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('0102', '系统管理', NULL, '01', 'manager', '后台管理-系统管理');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010201', '地区', NULL, '0102', 'manager', '后台管理-系统管理-地区');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020101', '查询地区列表', '/area/list', '010201', 'manager', '后台管理-系统管理-地区-查询地区列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020102', '查询地区树', '/area/tree', '010201', 'manager', '后台管理-系统管理-地区-查询地区树');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010202', '字典', NULL, '0102', 'manager', '后台管理-系统管理-字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020201', '新增字典', '/dict/add', '010202', 'manager', '后台管理-系统管理-字典-新增字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020202', '删除字典', '/dict/del', '010202', 'manager', '后台管理-系统管理-字典-删除字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020203', '查询单条字典', '/dict/find', '010202', 'manager', '后台管理-系统管理-字典-查询单条字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020204', '查询字典列表', '/dict/list', '010202', 'manager', '后台管理-系统管理-字典-查询字典列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020205', '修改字典', '/dict/mod', '010202', 'manager', '后台管理-系统管理-字典-修改字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020206', '分页查询字典', '/dict/page', '010202', 'manager', '后台管理-系统管理-字典-分页查询字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020207', '字典上移', '/dict/up', '010202', 'manager', '后台管理-系统管理-字典-字典上移');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020208', '字典下移', '/dict/down', '010202', 'manager', '后台管理-系统管理-字典-字典下移');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020209', '查询字典树', '/dict/tree', '010202', 'manager', '后台管理-系统管理-字典-查询字典树');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020210', '查询列表字典', '/dict/dictList', '010202', 'manager', '后台管理-系统管理-字典-查询列表字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020211', '查询全集字典', '/dict/dictMap', '010202', 'manager', '后台管理-系统管理-字典-查询全集字典');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010203', '参数', NULL, '0102', 'manager', '后台管理-系统管理-参数');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020301', '新增参数', '/param/add', '010203', 'manager', '后台管理-系统管理-参数-新增参数');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020302', '删除参数', '/param/del', '010203', 'manager', '后台管理-系统管理-参数-删除参数');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020303', '查询单条参数', '/param/find', '010203', 'manager', '后台管理-系统管理-参数-查询单条参数');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020304', '查询参数列表', '/param/list', '010203', 'manager', '后台管理-系统管理-参数-查询参数列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020305', '修改参数', '/param/mod', '010203', 'manager', '后台管理-系统管理-参数-修改参数');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020306', '分页查询参数', '/param/page', '010203', 'manager', '后台管理-系统管理-参数-分页查询参数');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010204', '日志', NULL, '0102', 'manager', '后台管理-系统管理-日志');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020401', '新增日志', '/log/add', '010204', 'manager', '后台管理-系统管理-日志-新增日志');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020402', '查询单条日志', '/log/find', '010204', 'manager', '后台管理-系统管理-日志-查询单条日志');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020403', '分页查询日志', '/log/page', '010204', 'manager', '后台管理-系统管理-日志-分页查询日志');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010205', '附件板块', NULL, '0102', 'manager', '后台管理-系统管理-附件板块');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020501', '新增附件板块', '/bucket/add', '010205', 'manager', '后台管理-系统管理-附件板块-新增附件板块');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020502', '删除附件板块', '/bucket/del', '010205', 'manager', '后台管理-系统管理-附件板块-删除附件板块');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020503', '查询单条附件板块', '/bucket/find', '010205', 'manager', '后台管理-系统管理-附件板块-查询单条附件板块');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020504', '查询附件板块列表', '/bucket/list', '010205', 'manager', '后台管理-系统管理-附件板块-查询附件板块列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020505', '修改附件板块', '/bucket/mod', '010205', 'manager', '后台管理-系统管理-附件板块-修改附件板块');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020506', '分页查询附件板块', '/bucket/page', '010205', 'manager', '后台管理-系统管理-附件板块-分页查询附件板块');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010206', '附件信息', NULL, '0102', 'manager', '后台管理-系统管理-附件信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020601', '新增附件信息', '/attach/add', '010206', 'manager', '后台管理-系统管理-附件信息-新增附件信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020602', '删除附件信息', '/attach/del', '010206', 'manager', '后台管理-系统管理-附件信息-删除附件信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020603', '查询单条附件信息', '/attach/find', '010206', 'manager', '后台管理-系统管理-附件信息-查询单条附件信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020604', '查询附件信息列表', '/attach/list', '010206', 'manager', '后台管理-系统管理-附件信息-查询附件信息列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020605', '修改附件信息', '/attach/mod', '010206', 'manager', '后台管理-系统管理-附件信息-修改附件信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020606', '分页查询附件信息', '/attach/page', '010206', 'manager', '后台管理-系统管理-附件信息-分页查询附件信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020607', '保存附件信息', '/attach/save', '010206', 'manager', '后台管理-系统管理-应用版本-保存附件信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('010207', '应用版本', NULL, '0102', 'manager', '后台管理-系统管理-应用版本');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020701', '新增应用版本', '/appVersion/add', '010207', 'manager', '后台管理-系统管理-应用版本-新增应用版本');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020702', '删除应用版本', '/appVersion/del', '010207', 'manager', '后台管理-系统管理-应用版本-删除应用版本');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020703', '查询单条应用版本', '/appVersion/find', '010207', 'manager', '后台管理-系统管理-应用版本-查询单条应用版本');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020704', '查询应用版本列表', '/appVersion/list', '010207', 'manager', '后台管理-系统管理-应用版本-查询应用版本列表');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020705', '修改应用版本', '/appVersion/mod', '010207', 'manager', '后台管理-系统管理-应用版本-修改应用版本');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020706', '分页查询应用版本', '/appVersion/page', '010207', 'manager', '后台管理-系统管理-应用版本-分页查询应用版本');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020707', '查询应用最新版本信息', '/appVersion/currVersion', '010207', 'manager', '后台管理-系统管理-应用版本-查询应用最新版本信息');
INSERT INTO sys_api (api_id, api_name, url, parent_id, sys_id, description) VALUES ('01020708', '保存应用版本信息', '/appVersion/save', '010207', 'manager', '后台管理-系统管理-应用版本-保存应用版本信息');
